version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.4.0
    steps:
      - checkout
      - run:
          name: Install Yarn
          command: curl -o- -L https://yarnpkg.com/install.sh | bash && yarn --version
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install npm dependencies
          command: yarn
      - run:
          name: Run test suite
          command: yarn test
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
workflows:
  version: 2
  test:
    jobs:
      - test
